site_name: Latency Monitor
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_name: mirceaulinic/latency-monitor
repo_url: https://github.com/mirceaulinic/latency-monitor
theme:
  name: dracula
  logo: images/logo_small.png
  favicon: images/favicon.png
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - glightbox
nav:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - Docker: docker.md
  - Architecture: arch.md
  - Metrics Backends:
    - Cli: metrics/cli.md
    - Log: metrics/log.md
    - ZeroMQ: metrics/zeromq.md
    - Datadog: metrics/datadog.md
    - ClickHouse: metrics/clickhouse.md
    - Pushgateway: metrics/pushgateway.md
